//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class covidDetail
    {
        public int code { get; set; }
        public Nullable<int> idMember { get; set; }
        public Nullable<int> numOfVaccination { get; set; }
        public string manufacturerVaccination { get; set; }
        public Nullable<System.DateTime> vaccinationDate { get; set; }
    
        public virtual HMOmember HMOmember { get; set; }
    }
}
