//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMOmember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HMOmember()
        {
            this.covidDetails = new HashSet<covidDetail>();
        }
    
        public int id { get; set; }
        public string memberName { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string telephone { get; set; }
        public string cellphone { get; set; }
        public Nullable<System.DateTime> positiveDate { get; set; }
        public Nullable<System.DateTime> negativeDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<covidDetail> covidDetails { get; set; }
    }
}
